# Generated by Django 4.1.1 on 2022-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('variety', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('price_exvat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_incvat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_level', models.PositiveIntegerField()),
            ],
        ),
    ]
