# Generated by Django 4.1.1 on 2022-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='description',
            field=models.TextField(default='This wine has no description.'),
        ),
    ]
