# Generated by Django 4.1.1 on 2022-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfront', '0002_wine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_filename',
            field=models.CharField(default='wine_placeholder.png', max_length=100),
        ),
    ]
