# Generated by Django 4.1.1 on 2022-10-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfront', '0003_wine_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
