# Generated by Django 4.1.1 on 2022-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopfront', '0004_remove_wine_image_filename_wine_image_wine_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/'),
        ),
    ]
